#ifndef H_PINOUT
#define H_PINOUT

#define BUZZER_PIN GPIO_PIN_10
#define BUZZER_PORT GPIOB

#define BUTTON_PIN GPIO_PIN_15
#define BUTTON_PORT GPIOC

#define SELF_HOLD_PIN GPIO_PIN_2
#define SELF_HOLD_PORT GPIOB



#define USART_MB1 USART1
#define USART_MB1_TX_PIN GPIO_PIN_2
#define USART_MB1_TX_PORT GPIOA
#define USART_MB1_RX_PIN GPIO_PIN_3
#define USART_MB1_RX_PORT GPIOA





#endif
